import {execFile} from 'node:child_process';
import {existsSync} from 'node:fs';
import {mkdir, readFile, writeFile} from 'node:fs/promises';
import {randomBytes, randomUUID, X509Certificate} from 'node:crypto';
import {generateSelfSignedCertificate} from './selfsigned.js';
import {promisify} from 'node:util';
import os from 'node:os';
import path from 'node:path';
import { defaultNodeCapabilities } from '../../adapters/host.js';
import { preferredDeviceName } from '../../packages/platform/identity.js';

// First run on the computer that will BE USED must produce a working identity by itself:
// device id, token, TLS certificate and a usable configuration. No hand editing, no commands
// the user has to look up, and no external tool: the certificate is generated by node:crypto so
// a fresh Windows machine works the same as macOS. openssl is only used when a caller asks for it.

const exec = promisify(execFile);

export interface SetupResult { config: string; cert: string; key: string; device_id: string; name: string;
  tls_server_name: string; token: string; fingerprint: string; created: boolean }

export function defaultConfig(overrides: Partial<Record<string, unknown>> = {}) {
  const name = os.hostname();
  const id = randomUUID();
  return {
    device_id: id,
    name,
    host: '0.0.0.0',
    port: 7443,
    token: randomBytes(32).toString('hex'),
    cert: '', key: '',
    allowed_roots: [],
    mode: 'developer',
    capabilities: defaultNodeCapabilities(),
    audit: '', kill_switch: '', tasks_dir: '',
    ...overrides,
  };
}

export function tlsNameFor(deviceId: string) { return 'agentlink-' + deviceId + '.local'; }

export async function generateIdentity(directory: string, deviceId: string, options: { openssl?: string } = {}) {
  await mkdir(directory, { recursive: true, mode: 0o700 });
  const name = tlsNameFor(deviceId);
  const cert = path.join(directory, 'node-cert.pem');
  const key = path.join(directory, 'node-key.pem');
  if (!existsSync(cert) || !existsSync(key)) {
    // Only an explicitly named, working openssl is used; otherwise the built-in generator runs.
    // A hard dependency here is what used to make Windows impossible without a compiled app.
    const openssl = options.openssl ?? '';
    if (openssl && existsSync(openssl)) {
      await exec(openssl, ['req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-keyout', key, '-out', cert,
        '-days', '3650', '-subj', '/CN=' + name,
        '-addext', 'subjectAltName=DNS:' + name + ',DNS:localhost,IP:127.0.0.1',
        '-addext', 'extendedKeyUsage=serverAuth'], { timeout: 60000 });
    } else {
      const generated = generateSelfSignedCertificate({ commonName: name,
        dnsNames: [name, 'localhost'], ipAddresses: ['127.0.0.1'], days: 3650 });
      await writeFile(cert, generated.cert, { mode: 0o600 });
      await writeFile(key, generated.key, { mode: 0o600 });
    }
  }
  const pem = await readFile(cert, 'utf8');
  const parsed = new X509Certificate(pem);
  return { cert, key, tls_server_name: name, fingerprint: parsed.fingerprint256 };
}

export interface SetupOptions { directory?: string; roots?: string[]; port?: number; shareRoot?: string; openssl?: string }

// Creates or repairs the node configuration. Existing credentials are preserved.
export async function setupNode(options: SetupOptions = {}): Promise<SetupResult> {
  const directory = path.resolve(options.directory ?? path.join(os.homedir(), '.agentlink-node'));
  const configPath = path.join(directory, 'node.local.json');
  await mkdir(directory, { recursive: true, mode: 0o700 });
  let config: Record<string, unknown>;
  let created = false;
  try {
    config = JSON.parse(await readFile(configPath, 'utf8')) as Record<string, unknown>;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT')
      throw new Error('Existing node configuration is unreadable; refusing to replace its identity');
    created = true;
    const home = os.homedir();
    config = defaultConfig({ name: await preferredDeviceName() });
    // The share folder is chosen before anything is created, so --share never loses to a default.
    const explicit = options.roots ?? [];
    // A default share folder is only invented when the caller named no folder at all;
    // an explicit list must be used exactly as given.
    const shared = options.shareRoot ?? (explicit.length ? null : path.join(home, 'AgentLinkShare'));
    config.allowed_roots = [...new Set([...(shared ? [shared] : []), ...explicit])];
    if (options.port) config.port = options.port;
    config.audit = path.join(directory, 'audit.jsonl');
    config.kill_switch = path.join(directory, 'DISABLE_AGENT_ACCESS');
    config.tasks_dir = path.join(directory, 'tasks');
    for (const root of config.allowed_roots as string[]) await mkdir(root, { recursive: true, mode: 0o700 });
  }
  const identity = await generateIdentity(directory, String(config.device_id), { openssl: options.openssl });
  config.cert = identity.cert;
  config.key = identity.key;
  config.tls_server_name = identity.tls_server_name;
  if (options.shareRoot) config.allowed_roots = [...new Set([...(config.allowed_roots as string[] ?? []), options.shareRoot])];
  for (const root of config.allowed_roots as string[]) await mkdir(root, { recursive: true, mode: 0o700 });
  await writeFile(configPath, JSON.stringify(config, null, 2) + '\n', { mode: 0o600 });
  return { config: configPath, cert: identity.cert, key: identity.key, device_id: String(config.device_id),
    name: String(config.name), tls_server_name: identity.tls_server_name, token: String(config.token),
    fingerprint: identity.fingerprint, created };
}
